name: Monitor

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '*/10 * * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests #安装模块
      run: |
        pip install requests
        pip install lxml
        pip install selenium
        pip install browsermob-proxy
    - name: run
      run: |
        sudo cp -p ./chrome/chromedriver /usr/bin/
        #sudo cp -p ./chrome/browsermob-proxy /usr/bin/
        chmod -R 777 /usr/bin/chromedriver
        #chmod -R 777 /usr/bin/browsermob-proxy
        chmod -R 777 ./Spider
        python ./Spider/main.py
        
